[build]
  base = "/"
  publish = "/.next"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[context.production]
  command = "npm ci && npm run build"
  publish = "/.next"
  base = "/"

[context.production.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_BASE_PATH = ""
